[project]
name = "pdesy"
version = "0.8.0"
description = "pDESy: Discrete Event Simulation of Python"
authors = [
    {name = "Taiga MITSUYUKI",email = "mitsuyuki-taiga-my@ynu.ac.jp"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.4,<3.0.0",
    "tqdm>=4.67.1,<5.0.0",
]

[project.optional-dependencies]
vis = [
    "networkx>=3.4.2,<4.0.0",
    "matplotlib>=3.10.1,<4.0.0",
    "plotly>=6.1.1,<7.0.0",
    "kaleido>=1.2.0,<2.0.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3,<10.0.0",
    "flake8>=7.2.0,<8.0.0",
    "autopep8>=2.3.2,<3.0.0",
    "black>=26.3.1,<27.0.0",
    "pytest-cov>=6.1.1,<7.0.0",
    "sphinx>=7.0.0,<8.0.0",
    "sphinx-rtd-theme>=2.0.0,<3.0.0",
    "pylint>=3.3.8,<4.0.0",
    "ipykernel>=7.1.0,<8.0.0",
]
docs = [
    "sphinx>=7.0.0,<8.0.0",
    "sphinx-rtd-theme>=2.0.0,<3.0.0",
]


[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pDESy"]

[tool.pylint.'FORMAT']
good-names = ["ID"]
